### ISSUE TITLE
Remove hardcoded parameters from convert_trained_model_to_framework.py

### ISSUE THREAD

**Issue by jiazou-bigdata** [asu-cactus/netsdb#32]
Now the number of features is hard-coded: e.g.:

https://github.com/asu-cactus/netsdb/blob/master/model-inference/decisionTree/experiments/convert_trained_model_to_framework.py#L123

https://github.com/asu-cactus/netsdb/blob/master/model-inference/decisionTree/experiments/convert_trained_model_to_framework.py#L152

Can we put the number of features of each dataset to the config.json, and extract the value instead of hard-coding it in convert_trained_model_to_framework.py?

**Comment by hguan6** [comment]
Yes. I will look into it.

**Comment by jiazou-bigdata** [comment]
This issue is fixed in pull [request 33](https://github.com/asu-cactus/netsdb/pull/33). Thanks Hong.
