### ISSUE TITLE
Support a TPC-AI Scenario for decision forest support

### ISSUE THREAD

**Issue by jiazou-bigdata** [asu-cactus/netsdb#57]
Fraud detection Use Case 10: https://www.tpc.org/tpc_documents_current_versions/pdf/tpcx-ai_v1.0.2.pdf

**Comment by venkate5hgunda** [comment]
Training with Scale Factor 1 (1GB) on SkLearn.

Testing, at the moment with Scale Factors 1, 3, 10.
